CasAvanguardia/urls.py
from realestate_activity.views import AppointmentView, DeleteAppointmentView
from .settings import MEDIA_URL, MEDIA_ROOT
from django.contrib import admin
from django.urls import path, include
from CasAvanguardia.views import Homepage, contact_view, self_candidacy
from django.conf.urls.static import static

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('contact', contact_view, name='contacts'),
    path('lavora-con-noi', self_candidacy, name='work-together'),
    path('appointment', AppointmentView.as_view(), name='appointment'),
    path('appointment/delete-appointments', DeleteAppointmentView.as_view(), name='delete-appointment'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('activity/', include('realestate_activity.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

realestate_activity/urls.py
from django.urls import path
from realestate_activity.views import *

app_name = 'activity'  # all the names in urlpattern will be preceded by this value

urlpatterns = [
    path('agenti', Agents.as_view(), name="agents"),
    path('vendita', sell_request, name="sell-house"),
    path('valutazione', rate_request, name="rate-house"),
    path('inserisci-annuncio', InsertProperty.as_view(), name="insert-property"),
    path('<int:pk>/detail', PropertyDetail.as_view(), name="detail-property"),
    path('<int:pk>/update', UpdateDetail.as_view(), name="update-property"),
    path('<int:pk>/delete', DeleteDetail.as_view(), name="delete-property"),
    path('lista', AllProperties.as_view(), name="all-properties"),
    path('inserisci-agente', InsertAgent.as_view(), name="insert-agent"),
    path('<int:pk>/agent-detail', AgentDetail.as_view(), name="agent-detail"),
    path('<int:pk>/agent-delete', DeleteAgent.as_view(), name="delete-agent"),
    path('<int:pk>/agent-update', UpdateAgent.as_view(), name="update-agent"),
    path('<int:pk>/recensione-agente', RatingView.as_view(), name="rate-agent"),
    path('appointment', AppointmentView.as_view(), name='appointment'),
    path('appointment/delete-appointments', DeleteAppointmentView.as_view(), name='delete-appointment'),
]

users/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy
from users.views import UserCreateView, UserUpdateView, UserDeleteView
from django.contrib.auth import views as auth_views
app_name = 'users'  # all the names in urlpattern will be preceded by this value

urlpatterns = [
    path('user_create/', UserCreateView.as_view(), name="user-create"),
    path('<int:pk>/user_update/', UserUpdateView.as_view(), name="user-update"),
    path('<int:pk>/user_delete/', UserDeleteView.as_view(), name="user-delete"),
    path('login/', auth_views.LoginView.as_view(template_name='users/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/registration/logged_out.html'), name='logout'),
    path('password/', auth_views.PasswordChangeView.as_view(template_name="users/registration/CRUD/change_password.html",
                                                            success_url=reverse_lazy('homepage')),
         name='change_password'),
]

templates/contact.html
{% extends 'realestate_activity/base-form.html' %}
{% load static %}

{% block title %}
    <title>MaSCasa - Contacts</title>
{% endblock %}

{% block content %}
    <main id="main">
        <section class="intro-single">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="title-single-box">
                            <h1 class="title-single">Contacts</h1>
                            <span class="color-text-a">{% lorem %}</span>
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-4">
                        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="{% url 'homepage' %}">Home</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Contacts
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </section>

        <section class="contact">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="contact-map box">
                            <div id="map" class="contact-map">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2834.5874609664356!2d10.614690215359374!3d44.72803039028191!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47801c0238464471%3A0xbde27a28cf8fbc97!2sVia%20Umberto%20Degola%2C%201%2C%2042124%20Reggio%20Emilia%20RE!5e0!3m2!1sen!2sit!4v1626383345217!5m2!1sen!2sit" width="100%" height="450" style="border:0" allowfullscreen loading="lazy"></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 section-t8">
                        <div class="row">
                            <div class="col-md-7">
                                <form method="POST" class="w-75 align-items-center">{% csrf_token %}
                                    <div class="row">
                                        <div class="col col-sm-6">
                                            <div class="form-group">
                                                <label for="inputName">Name *</label>
                                                <input type="text" name="name" class="form-control" id="inputName" placeholder="Your name" required>
                                            </div>
                                        </div>
                                        <div class="col col-sm-6">
                                            <div class="form-group">
                                                <label for="inputName">Surname *</label>
                                                <input type="text" name="surname" class="form-control" id="inputName" placeholder="Your surname" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="form-group">
                                                <label for="inputEmail">Email *</label>
                                                <input type="text" name="email" class="form-control" id="inputEmail" value="{{ user.email }}" required>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="form-group">
                                                <label for="inputPhone">Phone *</label>
                                                <input type="text" name="phone" class="form-control" id="inputPhone" value="{{ user.phone }}" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <label for="inputSubject">Subject *</label>
                                            <input id="inputSubject" name="subject" class="form-control" placeholder="Subject" required>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <label for="inputMessage">Message *</label>
                                            <textarea id="inputMessage" name="message" class="form-control" cols="45" rows="8" placeholder="What's your request?" required></textarea>
                                        </div>
                                    </div>
                                    <small class="form-text text-muted">We won't use these data with third parties</small><br/>
                                    <input type="submit" value="Send" class="btn btn-success mt-4">
                                </form>
                            </div>
                            <div class="col-md-5 section-md-t3">
                                <div class="icon-box section-b2">
                                    <div class="icon-box-icon">
                                        <span class="bi bi-envelope"></span>
                                    </div>
                                    <div class="icon-box-content table-cell">
                                        <div class="icon-box-title">
                                            <h4 class="icon-title">Contact us</h4>
                                        </div>
                                        <div class="icon-box-content">
                                            <p class="mb-1">Email
                                                <span class="color-a">mascasa.team@mascasa.com</span>
                                            </p>
                                            <p class="mb-1">Phone
                                                <span class="color-a">+39 123 4567890</span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="icon-box section-b2">
                                    <div class="icon-box-icon">
                                        <span class="bi bi-geo-alt"></span>
                                    </div>
                                    <div class="icon-box-content table-cell">
                                        <div class="icon-box-title">
                                            <h4 class="icon-title">Come and visit us</h4>
                                        </div>
                                        <div class="icon-box-content">
                                            <p class="mb-1">
                                                Via Umberto Degola, 1
                                                <br> 42124 Reggio Emilia RE
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="m-4">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }} text-success" style="list-style: none" {% endif %}><strong>{{ message }}</strong></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        </section>

    </main>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>MaSCasa - Home</title>
{% endblock %}

{% block content %}
    {% if user.is_authenticated and user.owner %}
        <section class="section-t8">
            <h1 style="padding-left: 50px;">Owner section</h1>
            <div class="row">
                <div class="col">
                    <form class="mt-5 p-5 align-items-center">
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 col-form-label">Username</label>
                            <div class="col-sm-10">
                                <input id="inputName" class="form-control" type="text" disabled value="{{ user.username }}" name="name"/>
                            </div>
                        </div>
                        <br/>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                <input id="inputEmail" class="form-control" type="email" disabled value="{{ user.email }}" name="email"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPhone" class="col-sm-2 col-form-label">Phone</label>
                            <div class="col-sm-10">
                                <input id="inputPhone" class="form-control" type="tel" disabled value="{{ user.phone }}" name="phone">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col text-center my-auto">
                    <a href="{% url 'activity:insert-property' %}">
                        <button class="btn btn-success" style="padding: 40px 30px; font-size: 25px">Insert a new ad</button>
                    </a>
                </div>
                <div class="col text-center my-auto">
                    <a href="{% url 'activity:insert-agent' %}">
                        <button class="btn btn-success" style="padding: 40px 30px; font-size: 25px">Insert a new agent</button>
                    </a>
                </div>
            </div>
        </section>
    {% endif %}

    <main id="main">
        <section class="section-news section-t8">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="title-wrap d-flex justify-content-between">
                            <div class="title-box">
                                <h2 class="title-a">Newest ads</h2>
                            </div>
                            <div class="title-link">
                                <a href="{% url 'activity:all-properties' %}">All ads
                                    <span class="bi bi-chevron-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="news-carousel" class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for property in latest_properties %}
                            <div class="carousel-item-a swiper-slide">
                                <div class="card-box-b card-shadow news-box" style="object-fit: contain; width: 400px; height: 450px;">
                                    <div class="img-box-b">
                                        <img src="{{ property.image.url }}" alt="Ad{{ forloop.counter }} pic" class="img-b img-fluid">
                                    </div>
                                    <div class="card-overlay">
                                        <div class="card-header-b">
                                            <div class="card-category-b">
                                                <a class="category-b">{{ property.contr }}</a>
                                            </div>
                                            <div class="card-title-b">
                                                <h2 class="title-2">
                                                    <a href="{% url 'activity:detail-property' property.pk %}">{{ property.address }}</a>
                                                </h2>
                                            </div>
                                            <div class="card-date">
                                                <span class="date-b">{{ property.insertion_date }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="news-carousel-pagination carousel-pagination"></div>
            </div>
        </section>

        <section class="section-agents section-t8">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="title-wrap d-flex justify-content-between">
                            <div class="title-box">
                                <h2 class="title-a">Best agents</h2>
                            </div>
                            <div class="title-link">
                                <a href="{% url 'activity:agents' %}">All agents
                                    <span class="bi bi-chevron-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for agent in top_agents %}
                        <div class="col-md-4">
                            <div class="card-box-d" style="object-fit: contain; width: 400px; height: 400px;">
                                <div class="card-img-d">
                                    <img src="{{ agent.image.url }}" alt="Top-agent{{ forloop.counter }} pic" class="img-d img-fluid">
                                </div>
                                <div class="card-overlay card-overlay-hover">
                                    <div class="card-header-d">
                                        <div class="card-title-d align-self-center">
                                            <h3 class="title-d">
                                                <a href="{% url 'activity:agent-detail' agent.pk %}" class="link-two">{{ agent.name }} {{ agent.surname }}</a>
                                            </h3>
                                        </div>
                                    </div>
                                    <div class="card-body-d">
                                        <div class="info-agents color-a">
                                            <p>
                                                <strong>Phone: </strong> {{ agent.phone }}
                                            </p>
                                            <p>
                                                <strong>Email: </strong> {{ agent.email }}
                                            </p>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/work-with-us.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
    <title>MaSCasa - Work with us</title>
{% endblock %}

{% block content %}
    <div class="row " style="margin-top: 150px; padding-left: 50px">
        <div class="col-lg-5" >
            <h1 class="mb-2">Work with us</h1>
            <p>One of the cornerstones of our philosophy is the enhancement of human resources, in
                 particular of young people.<br>
                We want to foster a cohesive, young, dynamic and stimulating work environment.</p>
            <p>Each young person can count not only on his skills,
                 on the support of a group with a consolidated and structured professional method, on paths of
                 unique and particularly qualifying training and support on advanced technology and tools
                 innovative.</p>
            <p>
                <strong>Would you like to work in a real estate agency?</strong>
            </p>
            <p>
                <strong>Tell us who you are and what your goals are!</strong>
            </p>
            If you have a higher education or university education and a strong aptitude for interpersonal relationships,
             send us your Curriculum Vitae.<br>You will be able to start an interesting and dynamic profession, acquire
             multidisciplinary knowledge and have great satisfaction.
            <p></p>
        </div>
        <div class="col-lg-7">
            <h2>Send us your Curriculum Vitae</h2>
            <div class="mt-2 pt-2 ">
                <form method="POST" class="mt-5 p-5 align-items-center" enctype="multipart/form-data">{% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="inputName">Name *</label>
                                <input type="text" name="name" class="form-control" id="inputName" aria-describedby="emailHelp" placeholder="Your name" required>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="inputSurname">Surname *</label>
                                <input type="text" name="surname" class="form-control" id="inputSurname" placeholder="Your surname" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="inputCity">City</label>
                                <input type="text" name="city" class="form-control" id="inputCity" aria-describedby="emailHelp" placeholder="Your city">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="inputAddress">Address</label>
                                <input type="text" name="address" class="form-control" id="inputAddress" placeholder="Your address">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="inputAge">Age</label>
                                <input type="number" name="age" class="form-control" id="inputAge" aria-describedby="emailHelp">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="inputPhone">Phone *</label>
                                <input type="tel" name="phone" class="form-control" id="inputPhone" value="{{ user.phone }}" placeholder="Your phone number" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="inputEmail">Email *</label>
                                <input type="tel" name="email" class="form-control" id="inputEmail" value="{{ user.email }}" placeholder="Your email" required>
                                <small id="inputEmail" class="form-text text-muted">We won't use these data with third parties</small>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="uploadCV">Select your CV *</label>
                                <input type="file" accept=".doc,.docx,.pdf" name="cv" class="form-control-file" id="uploadCV" required>
                            </div>
                        </div>
                    </div>
                    <input type="submit" value="Apply" class="btn btn-success mt-4">
                    <a href="{% url 'homepage' %}" style="margin-left: 50px" class=" mt-4 btn btn-danger"><span>Cancel</span></a>
                </form>
            </div>
        </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} text-success" style="list-style: none" {% endif %}><strong>{{ message }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}