CasAvanguardia/urls.py
from realestate_activity.views import AppointmentView, DeleteAppointmentView
from .settings import MEDIA_URL, MEDIA_ROOT
from django.contrib import admin
from django.urls import path, include
from CasAvanguardia.views import Homepage, contact_view, self_candidacy
from django.conf.urls.static import static

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('contact', contact_view, name='contacts'),
    path('lavora-con-noi', self_candidacy, name='work-together'),
    path('appointment', AppointmentView.as_view(), name='appointment'),
    path('appointment/delete-appointments', DeleteAppointmentView.as_view(), name='delete-appointment'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('activity/', include('realestate_activity.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

realestate_activity/urls.py
from django.urls import path
from realestate_activity.views import *

app_name = 'activity'  # all the names in urlpattern will be preceded by this value

urlpatterns = [
    path('agenti', Agents.as_view(), name="agents"),
    path('vendita', sell_request, name="sell-house"),
    path('valutazione', rate_request, name="rate-house"),
    path('inserisci-annuncio', InsertProperty.as_view(), name="insert-property"),
    path('<int:pk>/detail', PropertyDetail.as_view(), name="detail-property"),
    path('<int:pk>/update', UpdateDetail.as_view(), name="update-property"),
    path('<int:pk>/delete', DeleteDetail.as_view(), name="delete-property"),
    path('lista', AllProperties.as_view(), name="all-properties"),
    path('inserisci-agente', InsertAgent.as_view(), name="insert-agent"),
    path('<int:pk>/agent-detail', AgentDetail.as_view(), name="agent-detail"),
    path('<int:pk>/agent-delete', DeleteAgent.as_view(), name="delete-agent"),
    path('<int:pk>/agent-update', UpdateAgent.as_view(), name="update-agent"),
    path('<int:pk>/recensione-agente', RatingView.as_view(), name="rate-agent"),
    path('appointment', AppointmentView.as_view(), name='appointment'),
    path('appointment/delete-appointments', DeleteAppointmentView.as_view(), name='delete-appointment'),
]

users/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy
from users.views import UserCreateView, UserUpdateView, UserDeleteView
from django.contrib.auth import views as auth_views
app_name = 'users'  # all the names in urlpattern will be preceded by this value

urlpatterns = [
    path('user_create/', UserCreateView.as_view(), name="user-create"),
    path('<int:pk>/user_update/', UserUpdateView.as_view(), name="user-update"),
    path('<int:pk>/user_delete/', UserDeleteView.as_view(), name="user-delete"),
    path('login/', auth_views.LoginView.as_view(template_name='users/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/registration/logged_out.html'), name='logout'),
    path('password/', auth_views.PasswordChangeView.as_view(template_name="users/registration/CRUD/change_password.html",
                                                            success_url=reverse_lazy('homepage')),
         name='change_password'),
]

realestate_activity/forms.py
import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from .models import Property, Agent, Rating, Appointment


class InsertPropertyForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = "w-75 align-items-center px-5"
    helper.add_input(Submit('submit', 'Add property', css_class="btn btn-success mt-2"))

    class Meta:
        model = Property
        fields = ['contract', 'typology', 'address', 'surface', 'price', 'image']


class UpdatePropertyForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = "w-75 align-items-center px-5"
    helper.add_input(Submit('submit', 'Update property', css_class="btn btn-success mt-2"))

    class Meta:
        model = Property
        fields = ['contract', 'typology', 'address', 'surface', 'price', 'image']


class InsertAgentForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = "w-75 align-items-center px-5"
    helper.add_input(Submit('submit', 'Add agent', css_class="btn btn-success mt-2"))

    class Meta:
        model = Agent
        fields = ['name', 'surname', 'email', 'phone', 'image']


class UpdateAgentForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = "w-75 align-items-center px-5"
    helper.add_input(Submit('submit', 'Update agent', css_class="btn btn-success mt-2"))

    class Meta:
        model = Agent
        fields = ['name', 'surname', 'email', 'phone', 'image']


class InsertRatingForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = "w-75 align-items-center px-5"
    helper.add_input(Submit('submit', 'Add review', css_class="btn btn-success mt-2"))

    class Meta:
        model = Rating
        fields = ['score', 'caption']  # the other fields are automatically set when compiling the form


class DateInput(forms.DateTimeInput):
    """
    Class to define a custom input type to use in the AppointmentForm
    """
    input_type = 'date'


class AppointmentForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = "w-50 align-items-center px-5"
    helper.add_input(Submit('submit', 'Reserve', css_class="btn btn-success mt-2"))

    class Meta:
        model = Appointment
        fields = ['date']
        widgets = {
            # defines a Date-like field with the today's date as the starting feasible value
            'date': DateInput(attrs={'min': datetime.date.today()})
        }

realestate_activity/views.py
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, redirect
import logging
from functools import reduce
import pandas as pd
from geopy.geocoders import Nominatim
import folium
from folium.plugins import MarkerCluster
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from CasAvanguardia.constants import TYPOLOGIES, CONTRACTS
from CasAvanguardia import settings
from realestate_activity.forms import InsertPropertyForm, UpdatePropertyForm, InsertAgentForm, UpdateAgentForm, \
    InsertRatingForm, AppointmentForm
from realestate_activity.models import Property, Agent, Rating, Appointment
from users.models import Client

_logger = logging.getLogger(__name__)


def send_mail_to_users(request):
    users_email = Client.objects.filter(owner=False).values('email')
    users_email_list = [e["email"] for e in users_email]

    subject = '[MaSCasa] There\'s a new message to you!'

    message = '<h2>Announce detail</h2><br/>' \
              '<p>Contract: ' + CONTRACTS[int(request.POST['contract'])] + \
              '</p><p>Typology: ' + TYPOLOGIES[int(request.POST['typology'])] + \
              '</p><p>Address: ' + request.POST['address'] + \
              '</p><p>Surface: ' + request.POST['surface'] + \
              'm<sup>2</sup></p><p>Price: €' + request.POST['price']+'</p>'

    send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, users_email_list, html_message=message)


def agent_avg_score(queryset):
    """
    Function to calculate the average score of an agent
    :param queryset: the object containing all the rating related to an agent
    :return: the average score based on the number of rating
    """
    if len(queryset) > 0:
        list_score = [q.score for q in queryset]
        sum_score = reduce(lambda a, b: a + b, list_score)
        return round(sum_score / len(queryset), 2)
    else:
        return 0


def order_results(order_price, order_surface, order_data):
    """
    Function to show the results of a search order by multiple aspects
    :param order_price: string filled with one between 'Crescente' and 'Decrescente' and '----'
    :param order_surface: same as for order_price but this time based on the squared meters of a property
    :param order_data: string filled with one between 'Più recenti' and 'Meno recenti' and '----'
    :return: list containing the order parameters to use to show the results
    """
    order_fields = ['price', 'surface', 'insertion_date']
    order_values = [order_price, order_surface, order_data]
    if order_price == '----':
        order_fields = order_fields[1:]
        order_values = order_values[1:]
    if order_surface == '----':
        order_fields = [order_fields[i] for i in [0, len(order_fields) - 1]]
        order_values = [order_values[i] for i in [0, len(order_values) - 1]]
    if order_data == '----':
        order_fields = order_fields[:len(order_fields) - 1]
        order_values = order_values[:len(order_values) - 1]

    for i, val in enumerate(order_values):
        if val == 'Decreasing' or val == 'Most recent':
            order_fields[i] = '-' + order_fields[i]  # to set a descending order

    return order_fields


def search_properties(self):
    """
    Function which implements the search through all the properties
    :param self: the instance of the view
    :return: a Queryset object with the searched items in the desired order
    """
    contract_filter = self.request.GET.get('contract')
    typology_filter = self.request.GET.get('typology')
    min_surface = int(self.request.GET.get('minSurface'))
    max_surface = int(self.request.GET.get('maxSurface'))
    min_price = int(self.request.GET.get('minPrice'))
    max_price = int(self.request.GET.get('maxPrice'))
    order_price = self.request.GET.get('orderPrice')
    order_surface = self.request.GET.get('orderArea')
    order_data = self.request.GET.get('orderData')

    base_queryset = Property.objects.filter(surface__range=[min_surface, max_surface],
                                            price__range=[min_price, max_price])

    if contract_filter == 'All':
        if typology_filter == 'All':
            queryset = base_queryset
        else:
            typology_filter = str(TYPOLOGIES.index(typology_filter))
            queryset = base_queryset.filter(typology=typology_filter)
    elif typology_filter == 'All':
        contract_filter = str(CONTRACTS.index(contract_filter))
        queryset = base_queryset.filter(contract=contract_filter)
    else:
        typology_filter = str(TYPOLOGIES.index(typology_filter))
        contract_filter = str(CONTRACTS.index(contract_filter))
        queryset = base_queryset.filter(contract=contract_filter,
                                        typology=typology_filter)

    order_fields = order_results(order_price, order_surface, order_data)

    return queryset.order_by(*order_fields)


def related_items(detail_object):
    """
    Function to realise a simple recommendation system based on some property parameters
    :param detail_object: the property the user is interested
    :return: an object containing the properties related to one property
    """

    # max: actual+20%; min: actual-20%
    max_price = int(detail_object.price + detail_object.price / 5)
    min_price = int(detail_object.price - detail_object.price / 5)
    min_surface = int(detail_object.surface - detail_object.surface / 5)
    max_surface = int(detail_object.surface + detail_object.surface / 5)

    base_related_items = Property.objects.filter(contract=detail_object.contract,
                                                 price__range=[min_price, max_price],
                                                 surface__range=[min_surface, max_surface])

    rel_items = base_related_items.filter(Q(id_i__gt=detail_object.id_i) |
                                          Q(id_i__lt=detail_object.id_i))  # to exclude the detail_object itself
    return rel_items


def create_map(df, zoom):
    """
    Function to return a map object to render in the preferred template
    :param df: a Dataframe containing the geo-localized addresses
    :param zoom: an int value to automatically zoom over the markers
    :return: a HTML representation of the processed map
    """
    mmap = folium.Map(location=df[["lat", "lon"]].mean().to_list(), zoom_start=zoom)

    marker_cluster = MarkerCluster().add_to(mmap)  # object to put the markers on
    for i, r in df.iterrows():
        location = (r["lat"], r["lon"])
        folium.Marker(location=location,
                      popup=r["address"],
                      tooltip=r["address"]).add_to(marker_cluster)

    mmap = mmap._repr_html_()  # the HTML representation of the map
    return mmap


def render_map(context):
    """
    Function to pass a map in a specified field of the context object
    :param context: the context object
    :return: the context with the 'map' key pointing the the HTML representation of the map to render
    """
    try:
        actual_address_list = [o.address for o in context["object_list"]]
        zoom = 12
    # the function is called either when retrieving just a single address (DetailView) and list o addresses (ListView)
    except KeyError:
        actual_address_list = [context["object"].address]
        zoom = 17  # higher zoom when there's just one object to display

    df = make_dataframe(actual_address_list)

    marker_map = create_map(df, zoom)
    context["map"] = marker_map

    return context


def make_dataframe(address_list):
    """
    Function to prepare the Dataframe containing the geo-localised addresses
    :param address_list: the list containing the addresses in string-format
    :return: the Dataframe instance
    """
    # if the object is not a list then is useless to keep processing it
    assert type(address_list) == list, AssertionError

    df = pd.DataFrame(address_list)
    df.columns = ['address']

    geolocator = Nominatim(user_agent="MasCasa app")  # instances the geolocator using the OpenStreetMap API

    df["loc"] = df["address"].apply(geolocator.geocode)
    df["point"] = df["loc"].apply(lambda loc: tuple(loc.point) if loc else None)
    df[['lat', 'lon', 'altitude']] = pd.DataFrame(df['point'].to_list(), index=df.index)

    return df


@login_required
def sell_request(request):
    """
    Function to process the request made to sell a property
    :param request: the request object
    :return: an HttpResponse whose content is filled with the result of the template sell-house.html
    """
    if request.method == 'POST' and request.POST['email']:
        subject = '['+ request.POST['purpose'] + ' Request] ' + request.POST['name'] + ' ' + request.POST['surname']

        message = '<h1>Contacts</h1>' \
                  '<p>Phone: ' + request.POST['phone'] + '</p><p>Email: ' + request.POST['email'] + \
                  '</p><h2>Additive infos:</h2><p>Indirizzo: ' + request.POST['address'] + '</p>' \
                                                                                                    '<p>Residential area: ' + \
                  request.POST['scope'] + \
                  '</p><p>Specific message: ' + request.POST['message'] + '</p>'

        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [settings.EMAIL_HOST_USER], html_message=message)

        messages.info(request, "Request correctly sent!")

    return render(request, 'realestate_activity/sell-house.html')


@login_required
def rate_request(request):
    """
    Function to process the request to have a free evaluation of a property
    :param request: the request object

realestate_activity/templates/realestate_activity/base-form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="p-5">

        {% block title-content %}{% endblock %}

        <form method="POST" class="mt-5 w-75 align-items-center">{% csrf_token %}
            <div class="row">
                <div class="col col-sm-6">
                    <div class="form-group">
                        <label for="inputName">Name *</label>
                        <input type="text" name="name" class="form-control" id="inputName" placeholder="Your name" required>
                    </div>
                </div>
                <div class="col col-sm-6">
                    <div class="form-group">
                        <label for="inputName">Surname *</label>
                        <input type="text" name="surname" class="form-control" id="inputName" placeholder="Your surname" required>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="inputEmail">Email *</label>
                        <input type="text" name="email" class="form-control" id="inputEmail" value="{{ user.email }}" required>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="inputPhone">Phone *</label>
                        <input type="text" name="phone" class="form-control" id="inputPhone" value="{{ user.phone }}" required>
                    </div>
                </div>
            </div>
            {% block additive-fields %}{% endblock %}
            <small class="form-text text-muted">We won't you these data with third parties</small><br/>
            <input type="submit" value="Send" class="btn btn-success mt-4">
            <a href="{% url 'homepage' %}" style="margin-left: 50px" class=" mt-4 btn btn-danger"><span>Cancel</span></a>
        </form>
    </div>
{% endblock %}

realestate_activity/templates/realestate_activity/delete-appointment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    <title>MaSCasa - Manage appointments</title>
{% endblock %}

{% block content %}
    <h1 style="margin-top: 150px">Manage your appointments</h1>

    <form class="m-3" method="GET">
        {% for app in object_list %}
            <div class="input-group w-25 mb-3">
                <input type="radio" name="radioButton{{ forloop.counter }}" class="m-3"/>
                <input type="text" name="appointment{{ forloop.counter }}" class="form-control"
                       style="background-color: white" value="{{ app.date }}"/>
            </div>
        {% endfor %}

        <button class="btn btn-danger">Delete</button>
    </form>
    <a href="{% url 'activity:appointment' %}" class="m-3">
        <button class="btn btn-secondary mt-3">Cancel</button>
    </a>
{% endblock %}

realestate_activity/templates/realestate_activity/get-appointment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    <title>MaSCasa - Get appointment</title>
{% endblock %}

{% block content %}
    <h1 style="margin-top: 150px">Welcome {{ user.username }}, get an appointment</h1>
    <div class="row">
        <div class="col">
            {% crispy form %}
        </div>
        <div class="col">
            <h4>My appointments</h4>
            <div class="m-3">
                {% for app in object_list %}
                    <div class="text-center form-control w-25 mb-3">{{ app.date }}</div>
                {% endfor %}
                <a href="{% url 'delete-appointment' %}">
                    <button name="updateAppointments" class="btn btn-success">Manage</button>
                </a>
            </div>
        </div>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} text-danger" style="list-style: none" {% endif %}><strong>{{ message }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

realestate_activity/templates/realestate_activity/rate-house.html
{% extends 'realestate_activity/base-form.html' %}
{% load static %}

{% block title %}
    <title>MaSCasa - Estimate your property</title>
{% endblock %}

{% block title-content %}
    <h1 style="margin-top: 150px">What's your house's value?</h1>
    <h2 class="text-success"></h2>
    <p>{{ user.address }}</p>
{% endblock %}

{% block additive-fields %}
    <div class="row">
        <div class="col">
            <div class="form-group mt-3">
                <label class="pb-2" for="scope">Typology *</label>
                <select class="form-control form-select form-control-a" id="scope" name="scope">
                    <option>Flat</option>
                    <option>Villa</option>
                    <option>Rustic</option>
                    <option>Box</option>
                </select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="inputSurface">Surface *</label>
                <input type="number" name="surface" class="form-control" id="inputSurface" required>
            </div>
        </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} text-success" style="list-style: none" {% endif %}><strong>{{ message }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

realestate_activity/templates/realestate_activity/rating.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>MaSCasa - Rate agent</title>
{% endblock %}

{% block content %}
    <h2 style="margin-top: 150px; padding-left: 30px">Send a review about {{ agent.name }} {{ agent.surname }}</h2>
    {% crispy form %}

    <a href="{% url 'activity:agent-detail' agent.pk %}" class="m-5">
        <button class="btn btn-danger mt-3">Cancel</button>
    </a>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} text-danger" style="list-style: none" {% endif %}><strong>{{ message }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

realestate_activity/templates/realestate_activity/sell-house.html
{% extends 'realestate_activity/base-form.html' %}
{% load static %}

{% block title %}
    <title>MaSCasa - Sell your house</title>
{% endblock %}

{% block title-content %}
    <h1 style="margin-top: 150px">Do you want to sell your house?</h1>
    <h2 class="text-success"></h2>
    <p>Trust our agency for a free evaluation! <br/>
       Thanks to our in-depth knowledge of the local market, we are able to carry out a market assessment in precise and timely terms.
         We will contact you to let you know our accurate evaluation.
        Fill out the following form. Thank you</p>
{% endblock %}

{% block additive-fields %}
    <div class="row">
        <div class="form-check-inline">
            <div class="col-md-12">
                <label for="sellType" class="radio">
                    <input id="sellType" name="purpose" checked="checked" type="radio" value="Sale">
                    Vendita
                </label>
                <label for="rentType" class="radio">
                    <input id="rentType" name="purpose" type="radio" value="Rent">
                Affitto
                </label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="inputAddress">Address *</label>
                <input type="text" name="address" class="form-control" id="inputAddress" value="{{ user.address }}" required>
            </div>
        </div>
        <div class="col">
            <div class="form-group mt-3">
                <label class="pb-2" for="scope">Residential type *</label>
                <select class="form-control form-select form-control-a" id="scope" name="scope">
                    <option>Studio flat</option>
                    <option>2 Rooms</option>
                    <option>3 Rooms</option>
                    <option>4 Rooms</option>
                    <option>5 Rooms</option>
                    <option>6 Rooms</option>
                    <option>Attic</option>
                    <option>Box</option>
                    <option>Loft</option>
                    <option>Farmland</option>
                    <option>Residential land</option>
                    <option>Semi-detached</option>
                    <option>Terraced house</option>
                    <option>Single Villa</option>
                    <option>Building</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <label for="inputMessage">Messagge </label>
            <input type="text" name="message" class="form-control" id="inputMessage">
        </div>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} text-success" style="list-style: none" {% endif %}><strong>{{ message }}</strong></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}